[[redirects]]
  from = "/*"
  to = "../error/400.html"
  status = 400

[[redirects]]
  from = "/*"
  to = "../error/401.html"
  status = 401

[[redirects]]
  from = "/*"
  to = "../error/403.html"
  status = 403

[[redirects]]
  from = "/*"
  to = "../error/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "../error/500.html"
  status = 500
